#!/usr/bin/env bash
# Configure an Nginx server so that /redirect_me is redirecting to another page with 301 Moved Permanently.

apt-get update
apt-get install -y nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sed -i "/server_name _;/ a\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
service nginx start
