#!/usr/bin/env bash
# Script that Installs haproxy and Configure HAproxy so that it send traffic to two servers

CONF="\
frontend my_fronted
    bind *:80
    mode http
    default_backend my_backend
    
backend my_backend
    balance roundrobin
    server web1 54.236.24.86:80 check
    server web2 18.233.63.71:80 check
"
apt-get -y update
apt-get -y install haproxy=2.0.\*
echo "$CONF" >> /etc/haproxy/haproxy.cfg
service haproxy start
