#!/usr/bin/env bash
# Script that Installs haproxy and Configure HAproxy so that it send traffic to two servers

CONF = "
frontend my_fronted
    bind *:80
    mode http
    default_backend my_backend
    
backend my_backend
    balance roundrobin
    server foo1 34.207.212.115:80 check
    server foo2 34.207.212.115:80 check
"
apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.0
apt-get -y update
apt-get -y install haproxy=2.0.\*
echo "$CONF" >> /etc/haproxy/haproxy.cfg
service haproxy start
