#!/usr/bin/env bash
# script that displays numbers from 1 to 20 and:
#
#  displays 4 and then bad luck from China for the 4th loop iteration
#  displays 9 and then bad luck from Japan for the 9th loop iteration
#  displays 17 and then bad luck from Italy for the 17th loop iteration
COUNTER=1
while [ $COUNTER -lt 21 ]; do
	echo $COUNTER
	if [ $COUNTER -eq 4 ]; then
		echo "bad luck from China"
	elif [ $COUNTER -eq 9 ]; then
		echo "bad luck from Japan"
	elif [ $COUNTER -eq 17 ]; then
		echo "bad luck from Italy"
	fi
	(( COUNTER++ ))
done
